version: '3.8'

services:
  application_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./development.ini:/usr/local/etc/php/php.ini
    networks:
      - interview_network
    depends_on:
      - database_service

  database_service:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: afaq
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: hatem
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - interview_network

  webserver_service:
    image: nginx:latest
    ports:
      - 9090:80
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - interview_network
    depends_on:
      - application_service

volumes:
  db_data:

networks:
  interview_network:
